package com.telecom.copilot_backend.service.impl;

import com.telecom.copilot_backend.dto.AuthResponse;
import com.telecom.copilot_backend.dto.LoginRequest;
import com.telecom.copilot_backend.dto.RegisterRequest;
import com.telecom.copilot_backend.entity.Customer;
import com.telecom.copilot_backend.repository.CustomerRepository;
import com.telecom.copilot_backend.security.CustomerUserDetails;
import com.telecom.copilot_backend.security.JwtUtil;
import com.telecom.copilot_backend.service.IAuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of IAuthService.
 * Handles customer authentication including login, registration, and JWT token management.
 */
@Service
@RequiredArgsConstructor
public class AuthServiceImpl implements IAuthService {

    private final CustomerRepository customerRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;
    private final AuthenticationManager authenticationManager;

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthResponse login(LoginRequest request) {
        Authentication authentication = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        request.getEmail(),
                        request.getPassword()
                )
        );

        CustomerUserDetails userDetails = (CustomerUserDetails) authentication.getPrincipal();
        String token = jwtUtil.generateToken(userDetails);

        return AuthResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .customerId(userDetails.getCustomerId())
                .name(userDetails.getName())
                .email(userDetails.getUsername())
                .build();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public AuthResponse register(RegisterRequest request) {
        // Validate email uniqueness (customerId will be auto-generated)
        if (customerRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException(
                    "Email '" + request.getEmail() + "' is already registered");
        }

        Customer customer = Customer.builder()
                // customerId is null, will be auto-generated by @UuidGenerator
                .customerId(null)
                .name(request.getName())
                .email(request.getEmail())
                .password(passwordEncoder.encode(request.getPassword()))
                .phoneNumber(request.getPhoneNumber())
                .tenureMonths(0)
                .build();

        customer = customerRepository.save(customer);

        CustomerUserDetails userDetails = new CustomerUserDetails(customer);
        String token = jwtUtil.generateToken(userDetails);

        return AuthResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .customerId(customer.getCustomerId())
                .name(customer.getName())
                .email(customer.getEmail())
                .build();
    }
}

