package com.telecom.copilot_backend.service.impl;

import com.telecom.copilot_backend.dto.CustomerDto;
import com.telecom.copilot_backend.dto.CustomerSearchCriteria;
import com.telecom.copilot_backend.entity.Customer;
import com.telecom.copilot_backend.entity.PlanCatalog;
import com.telecom.copilot_backend.exception.ResourceNotFoundException;
import com.telecom.copilot_backend.mapper.CustomerMapper;
import com.telecom.copilot_backend.repository.CustomerRepository;
import com.telecom.copilot_backend.repository.PlanCatalogRepository;
import com.telecom.copilot_backend.service.ICustomerService;
import com.telecom.copilot_backend.specification.CustomerSpecification;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Implementation of ICustomerService.
 * Handles all customer-related business logic operations with MapStruct mapping.
 */
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class CustomerServiceImpl implements ICustomerService {

    private final CustomerRepository customerRepository;
    private final PlanCatalogRepository planCatalogRepository;
    private final PasswordEncoder passwordEncoder;
    private final CustomerMapper customerMapper;

    /**
     * {@inheritDoc}
     */
    @Override
    public List<CustomerDto> getAllCustomers() {
        return customerRepository.findAll().stream()
                .map(customerMapper::toDto)
                .toList();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Page<CustomerDto> searchCustomers(CustomerSearchCriteria criteria, Pageable pageable) {
        // Create specification for dynamic filtering
        CustomerSpecification spec = new CustomerSpecification(criteria);
        // Execute query with pagination and filtering
        Page<Customer> customers = customerRepository.findAll(spec, pageable);
        // Convert entities to DTOs using mapper
        return customers.map(customerMapper::toDto);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerDto getCustomerById(String customerId) {
        return customerMapper.toDto(findEntityByCustomerId(customerId));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public CustomerDto createCustomer(CustomerDto dto) {
        // customerId will be auto-generated by Hibernate @UuidGenerator
        // Only validate that email is unique
        if (dto.getEmail() != null && customerRepository.existsByEmail(dto.getEmail())) {
            throw new IllegalArgumentException(
                    "Email '" + dto.getEmail() + "' is already registered");
        }
        Customer entity = customerMapper.toEntity(dto);
        // Set plan if provided
        if (dto.getCurrentPlanId() != null) {
            PlanCatalog plan = planCatalogRepository.findById(dto.getCurrentPlanId())
                    .orElseThrow(() -> new ResourceNotFoundException("Plan", "planId",
                            String.valueOf(dto.getCurrentPlanId())));
            entity.setCurrentPlan(plan);
        }
        // Encode password
        if (dto.getPassword() != null && !dto.getPassword().isBlank()) {
            entity.setPassword(passwordEncoder.encode(dto.getPassword()));
        }
        Customer saved = customerRepository.save(entity);
        return customerMapper.toDto(saved);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public CustomerDto updateCustomer(String customerId, CustomerDto dto) {
        Customer existing = findEntityByCustomerId(customerId);

        // Update mapped fields
        existing.setName(dto.getName());
        existing.setPhoneNumber(dto.getPhoneNumber());
        existing.setEmail(dto.getEmail());
        existing.setTenureMonths(dto.getTenureMonths());
        existing.setBillingCycleDate(dto.getBillingCycleDate());

        // Update password if provided
        if (dto.getPassword() != null && !dto.getPassword().isBlank()) {
            existing.setPassword(passwordEncoder.encode(dto.getPassword()));
        }

        // Update plan if provided
        if (dto.getCurrentPlanId() != null) {
            PlanCatalog plan = planCatalogRepository.findById(dto.getCurrentPlanId())
                    .orElseThrow(() -> new ResourceNotFoundException("Plan", "planId",
                            String.valueOf(dto.getCurrentPlanId())));
            existing.setCurrentPlan(plan);
        }

        Customer updated = customerRepository.save(existing);
        return customerMapper.toDto(updated);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void deleteCustomer(String customerId) {
        customerRepository.delete(findEntityByCustomerId(customerId));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Customer findEntityByCustomerId(String customerId) {
        return customerRepository.findById(customerId)
                .orElseThrow(() -> new ResourceNotFoundException("Customer", "customerId", customerId));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerDto toDto(Customer customer) {
        return customerMapper.toDto(customer);
    }
}



